name: Sync Multiple READMEs

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'python-api-agent-example/README.md'
      - 'ts-api-agent-example/README.md'

jobs:
  sync-readmes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout agent-tutorial repository
        uses: actions/checkout@v2

      - name: Checkout openserv-docs repository
        uses: actions/checkout@v2
        with:
          repository: 'openserv-labs/openserv-docs'
          token: ${{ secrets.GH_TOKEN }}
          path: 'openserv-docs'

      - name: Sync READMEs
        run: |
          cp README.md openserv-docs/packages/agent-tutorial/README.md
          cp python-api-agent-example/README.md openserv-docs/packages/agent-tutorial/python-api-agent-example/README.md
          cp ts-api-agent-example/README.md openserv-docs/packages/agent-tutorial/ts-api-agent-example/README.md
          
      - name: Commit and push if changed
        working-directory: ./openserv-docs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add packages/agent-tutorial/README.md
          git add packages/agent-tutorial/python-api-agent-example/README.md
          git add packages/agent-tutorial/ts-api-agent-example/README.md
          git commit -m "Update READMEs from agent-tutorial" || exit 0
          git push